<?php

declare(strict_types=1);

namespace Drupal\do_ops\Drush\Commands;

use Drupal\do_ops\Erd\ErdGenerator;
use Drush\Attributes as CLI;
use Drush\Commands\DrushCommands;

/**
 * `drush groups:erd` — emits a Mermaid ER diagram from entity/field metadata.
 *
 * See {@see ErdGenerator} for why this walks entity metadata rather than the
 * database schema (the DB declares zero foreign keys).
 */
class ErdCommands extends DrushCommands {

  public function __construct(
    private readonly ErdGenerator $generator,
  ) {
    parent::__construct();
  }

  /**
   * Generates a Mermaid ER diagram of the Groups entity schema.
   *
   * @param array $options
   *   The command options.
   *
   * @throws \InvalidArgumentException
   *   If `--scope` is not 'group' or 'all'.
   */
  #[CLI\Command(name: 'groups:erd', aliases: ['do:erd'])]
  #[CLI\Option(name: 'scope', description: "Either 'group' (group/group_type/group_role/group_relationship + directly-referenced entities) or 'all' (every entity type on the site). Defaults to 'group'.")]
  #[CLI\Option(name: 'out', description: 'Optional file path to write the diagram to. A .md path is wrapped in a titled Mermaid code fence; any other extension gets the raw erDiagram source. When omitted, the diagram is printed to stdout.')]
  public function erd(array $options = ['scope' => 'group', 'out' => NULL]): void {
    $scope = $options['scope'] ?? 'group';
    $diagram = $this->generator->generate($scope);

    $out = $options['out'] ?? NULL;
    if ($out === NULL) {
      $this->output()->write($diagram);
      return;
    }

    $contents = str_ends_with($out, '.md') ? $this->wrapAsMarkdown($diagram, $scope) : $diagram;
    if (file_put_contents($out, $contents) === FALSE) {
      throw new \RuntimeException(sprintf("Unable to write ER diagram to '%s'.", $out));
    }
    $this->logger()->success(sprintf('ER diagram (scope=%s) written to %s', $scope, $out));
  }

  /**
   * Wraps raw Mermaid source in a titled, fenced Markdown document.
   *
   * The wrapper is entirely deterministic (no timestamps, no run-specific
   * values) so re-running the command against unchanged site config produces
   * a byte-identical file — this is what makes a "regenerate and diff" CI
   * guard possible.
   */
  private function wrapAsMarkdown(string $diagram, string $scope): string {
    return <<<MD
# Groups Entity-Relationship Diagram

Generated by `drush groups:erd --scope={$scope}` from Drupal entity/field
metadata (not the database schema — see the `do_ops` ErdGenerator class
docblock for why). Do not hand-edit; regenerate and commit the diff instead.

```mermaid
{$diagram}```

MD;
  }

}
