#!/usr/bin/env bash
#
# assemble-config.sh — assemble the full groups-on-d11 config + custom modules.
#
# Single source of truth shared by the RUNBOOK (manual bring-up) and CI. The
# committed `config/sync` is only the Phase-1 baseline; the phase-2..7 config
# lives under `docs/groups/config/` and the custom `do_*` modules live under
# `docs/groups/modules/`. This script replicates the runbook assembly:
#
#   1. Copy every `docs/groups/config/*.yml` into `config/sync/`, EXCLUDING the
#      seven env-specific entries that carry drupal.org-environment dependencies
#      (TEST_PLAN.md §3.6 / RUNBOOK Step 190). Those are placed in the real
#      environment per Step 600h and must NOT land in a clean-room `config/sync`.
#   2. Copy the custom `do_*` modules from `docs/groups/modules/` into
#      `web/modules/custom/` so they can be enabled / tested.
#
# It is idempotent (plain copies, overwrite in place) and makes no DB changes —
# `config:import` / `drush en` are the caller's responsibility.
#
# BUILD OUTPUT IS NOT TRACKED. Everything this script writes is a build artifact,
# so a clean checkout followed by a build must leave `git status` clean:
#
#   * `web/modules/custom/` and `web/libraries/` are gitignored wholesale
#     (.gitignore) — same source-then-assemble pattern as assemble-libraries.sh.
#   * The files this script writes into `config/sync/` are gitignored via a
#     GENERATED `config/sync/.gitignore` (itself gitignored from the repo root),
#     regenerated below on every run from the actual copy set. That makes the
#     ignore list self-maintaining: adding a file to `docs/groups/config/`
#     needs no .gitignore edit. Only the genuine Phase-1 baseline entries — the
#     ones with no counterpart in `docs/groups/config/` — stay tracked.
#   * `core.extension.yml` is patched in place (§3 below), so its pristine
#     baseline lives in `docs/groups/config/core.extension.yml` (source of
#     truth) and only the patched copy lands in the untracked `config/sync/`.
#
# The `assemble-clean` job in .github/workflows/test.yml asserts
# `git status --porcelain` is empty after running this script, so any drift
# (e.g. a new `docs/groups/config/` file colliding with a still-tracked
# baseline entry, which needs a one-off `git rm --cached`) fails CI loudly
# instead of quietly re-dirtying every working tree.
#
# Usage:  scripts/ci/assemble-config.sh [REPO_ROOT]
#   REPO_ROOT defaults to the git top-level (or the script's grandparent dir).

set -euo pipefail

# Resolve the repository root.
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
REPO_ROOT="${1:-}"
if [[ -z "${REPO_ROOT}" ]]; then
  if REPO_ROOT="$(git -C "${SCRIPT_DIR}" rev-parse --show-toplevel 2>/dev/null)"; then
    :
  else
    REPO_ROOT="$(cd -- "${SCRIPT_DIR}/../.." >/dev/null 2>&1 && pwd -P)"
  fi
fi

CONFIG_SRC="${REPO_ROOT}/docs/groups/config"
CONFIG_DST="${REPO_ROOT}/config/sync"
MODULES_SRC="${REPO_ROOT}/docs/groups/modules"
MODULES_DST="${REPO_ROOT}/web/modules/custom"

# The seven env-specific configs to EXCLUDE from a clean-room config/sync.
# (TEST_PLAN.md §3.6 — three do_* blocks need the `bluecheese` theme,
#  pathauto.pattern.group_relationship needs pathauto, and user.role.community
#  + its two role actions reference Contact / drupal.org-only node types.)
EXCLUDE=(
  "block.block.do_contribution_stats.yml"
  "block.block.do_group_mission.yml"
  "block.block.do_profile_completeness.yml"
  "pathauto.pattern.group_relationship.yml"
  "user.role.community.yml"
  "system.action.user_add_role_action.community.yml"
  "system.action.user_remove_role_action.community.yml"
)

is_excluded() {
  local name="$1"
  for e in "${EXCLUDE[@]}"; do
    [[ "${name}" == "${e}" ]] && return 0
  done
  return 1
}

echo "==> assemble-config: repo root = ${REPO_ROOT}"

# --- 1. Assemble config/sync -------------------------------------------------
if [[ ! -d "${CONFIG_SRC}" ]]; then
  echo "ERROR: config source not found: ${CONFIG_SRC}" >&2
  exit 1
fi
mkdir -p "${CONFIG_DST}"

# Regenerate the ignore list for the build output. Written before/while copying
# so that even a half-finished run leaves no untracked artifacts behind.
CONFIG_IGNORE="${CONFIG_DST}/.gitignore"
cat > "${CONFIG_IGNORE}" <<'EOF'
# GENERATED by scripts/ci/assemble-config.sh — do not edit, do not commit.
# (This file is itself gitignored from the repo root.)
#
# Every entry below is build output copied from docs/groups/config/, which is
# the source of truth. Files in config/sync/ that are NOT listed here are the
# genuine tracked Phase-1 baseline.
/.gitignore
EOF

copied=0
skipped=0
for src in "${CONFIG_SRC}"/*.yml; do
  [[ -e "${src}" ]] || continue
  name="$(basename -- "${src}")"
  if is_excluded "${name}"; then
    skipped=$((skipped + 1))
    continue
  fi
  cp -f -- "${src}" "${CONFIG_DST}/${name}"
  printf '/%s\n' "${name}" >> "${CONFIG_IGNORE}"
  copied=$((copied + 1))
done
echo "==> config: copied ${copied} file(s), excluded ${skipped} env-specific file(s)"

if [[ "${skipped}" -ne "${#EXCLUDE[@]}" ]]; then
  echo "WARNING: excluded ${skipped} file(s) but expected ${#EXCLUDE[@]}; the env-specific set may have drifted from TEST_PLAN.md §3.6" >&2
fi

# --- 2. Copy custom do_* modules --------------------------------------------
if [[ ! -d "${MODULES_SRC}" ]]; then
  echo "ERROR: modules source not found: ${MODULES_SRC}" >&2
  exit 1
fi
mkdir -p "${MODULES_DST}"

modcount=0
MODULE_NAMES=()
for dir in "${MODULES_SRC}"/*/; do
  [[ -d "${dir}" ]] || continue
  name="$(basename -- "${dir}")"
  rm -rf -- "${MODULES_DST:?}/${name}"
  cp -R -- "${dir%/}" "${MODULES_DST}/${name}"
  MODULE_NAMES+=("${name}")
  modcount=$((modcount + 1))
done
echo "==> modules: copied ${modcount} custom module(s) into web/modules/custom/"

# --- 3. Register enabled modules in core.extension --------------------------
# The baseline `core.extension.yml` (source of truth:
# docs/groups/config/core.extension.yml, copied into config/sync above along
# with the rest of the phase-2..7 config) predates the do_* modules, so it does
# not list them (nor `flag`, which the assembled flag.* config depends on).
# The runbook enables these with `drush en` and re-exports; here we patch
# core.extension so the assembled config/sync is self-consistent — the do_tests
# kernel suite asserts do_group_extras / do_multigroup are enabled, and the
# clean-room `config:import` needs every module its config references present.
CORE_EXT="${CONFIG_DST}/core.extension.yml"
if [[ -f "${CORE_EXT}" ]]; then
  # Enable the copied custom modules (auto-discovered above into MODULE_NAMES,
  # which now includes do_chrome — the CH-F1 community-chrome/tooltip module,
  # #79) plus their non-custom hard dependencies that the assembled config
  # references but the baseline core.extension omits:
  #   - flag:             required by composer.json and the assembled flag.* config.
  #   - language:         hard dependency of do_group_language (do_group_language.info:
  #                       `drupal:language`); the assembled language.types.yml config
  #                       depends on it, so a clean-room `config:import` fails to install
  #                       do_group_language unless `language` is also enabled here.
  #   - message,
  #     message_notify:   hard dependencies of do_activity (#116); the assembled
  #                       do_activity config now references Message / Message Notify
  #                       templates, so a clean-room `config:import` fails to install
  #                       do_activity ("requires Message, Message Notify modules")
  #                       unless both are also enabled here.
  #   - geofield:         hard dependency of do_showcase (#125 SC-6); the assembled
  #                       field.storage.group.field_group_location.yml declares
  #                       `dependencies.module: [geofield]`, so a clean-room
  #                       `config:import` fails to install the field storage
  #                       unless geofield is also enabled here.
  # `pathauto` is intentionally NOT added: its one config entry is in the
  # excluded env-specific set (§3.6).
  ENABLE_MODULES="$(printf '%s\n' "${MODULE_NAMES[@]}" flag geofield language message message_notify)"
  export ENABLE_MODULES
  AUTOLOAD="${REPO_ROOT}/vendor/autoload.php"
  if [[ ! -f "${AUTOLOAD}" ]]; then
    echo "ERROR: ${AUTOLOAD} missing — run 'composer install' before assemble-config" >&2
    exit 1
  fi
  php -r '
    require $argv[2];
    $file = $argv[1];
    $ext = \Symfony\Component\Yaml\Yaml::parseFile($file);
    if (!isset($ext["module"]) || !is_array($ext["module"])) { $ext["module"] = []; }
    foreach (preg_split("/\s+/", trim(getenv("ENABLE_MODULES"))) as $m) {
      if ($m !== "" && !array_key_exists($m, $ext["module"])) { $ext["module"][$m] = 0; }
    }
    // Keep the module list sorted by weight then name, as Drupal exports it.
    uksort($ext["module"], function ($a, $b) use ($ext) {
      return [$ext["module"][$a], $a] <=> [$ext["module"][$b], $b];
    });
    file_put_contents($file, \Symfony\Component\Yaml\Yaml::dump($ext, 4, 2));
  ' "${CORE_EXT}" "${AUTOLOAD}" \
    || { echo "ERROR: failed to patch core.extension.yml" >&2; exit 1; }
  echo "==> core.extension: registered custom do_* modules + flag/geofield/language/message/message_notify as enabled"
else
  echo "WARNING: ${CORE_EXT} not found; skipping module registration" >&2
fi

echo "==> assemble-config: done"
